### ISSUE TITLE
Adapt Cray's pending PR to the new base

### ISSUE THREAD

**Issue by dongahn** [LLNL/LaunchMON#13]
We need to incorporate Cray's PR #7 into the new base with PR #12. It seems it would be most sensible to handpick the relevant changes and created a new PR.

**Comment by tgamblin** [comment]
They both look like they merge cleanly -- why not merge #7 then merge #12 and resolve the conflicts...?

**Comment by dongahn** [comment]
That is a reasonable idea. What should have done was to merge #7 first and rework for #12. 

I am not sure how much work will be needed to rebase to the new master if #7 is merged first with all the changes maded in #12. 

Will do some testing next week.

**Comment by tgamblin** [comment]
@dongahn: is LaunchMon using a rebase workflow?  You don't really have to rebase.  I find that it's often less work to fix things once in a merge commit than to rewrite history, but if you insist on a rebase workflow then you probably want to do this: `git config --global rerere.enabled 1`.  I find that helps a lot for avoiding the same conflict multiple times.  See [this blog post](https://medium.com/@porteneuve/fix-conflicts-only-once-with-git-rerere-7d116b2cec67#.wn78lbr83)

**Comment by dongahn** [comment]
Launchmon hasn't had strict protocols. After it grew about of a research project from source forge.

On a github repo, I tend to like rebasing because there commit history looks cleaner. I heard about rerere and thanks for the blog!

Dong


________________________________

**Comment by agontarek** [comment]
Hi all. I can have either Bob or Alex take a look at this. Note that we also have quite a few additional changes and bugfixes for CTI (Cray Tools Interface), a release of CTI is forthcoming. I am hoping that Bob/Alex is able to create a new pull request with these changes once CTI is released.

Note that I am no longer in the debugging tools group. I am now in the compiler group working on PGAS languages.

**Comment by dongahn** [comment]
@agontarek: Thanks!

If Bob and Alex have github IDs we can refer them here. 

What would be nice is if Cray folks can give a quick review for #20, we can merge that in first. I believe the change is reasonable and doesn't break any other environment so this should be an easy merge. 

Then, new PRs can be created and submitted on top of the new master? I don't want to lose this initial support in case we want to backport something from there or trying this on older systems...

**Comment by dongahn** [comment]
BTW, good luck with your PGAS project :-)

**Comment by dongahn** [comment]
We took liberty to merge this in. If Cray sees issues, we can always reopen the case.
