### ISSUE TITLE
Add level 0 CI support

### ISSUE THREAD

**Issue by dongahn** [LLNL/LaunchMON#15]
Please set up Travis CI testing. Without it, it will become increasingly hard to review and merge PRs with reasonable confidence. It will be a larger task to migrate all tests to the CI. This issues is just to add minimal support (e.g., being able to build again key configurations; install test etc). Over time, this should be a growth area.

**Comment by tgamblin** [comment]
@dongahn: FYI, level 0 could just `git clone spack` and `spack install launchmon`, if you want the nightly build to do integration testing (which seems reasonable to me).

If you want a more detailed breakdown of dependency builds, there is `spack test-install launchmon` which will run each node in the DAG as its own test case and spit out some XML to tell you which deps failed and which succeeded.  I don't think it takes that long to build `launchmon` or its deps, so this should be doable within Travis.

**Comment by dongahn** [comment]
nice!
