### ISSUE TITLE
Validate and fix LaunchMON tests for TOSS3

### ISSUE THREAD

**Issue by dongahn** [LLNL/LaunchMON#16]
As mentioned in PR #12, some of the tests don't run on LLNL's TOSS3 systems. 

```
opal186{dahn}22: uname -a 
Linux opal186 3.10.0-327.13.1.2chaos.ch6.x86_64 
x86_64 x86_64 GNU/Linux

opal186{dahn}25: rpm -qf /usr/bin/srun
slurm-2.3.3-1.19chaos.ch6.x86_64
```

Created the ticket to validate LaunchMON for these newer systems and fix problems like that.

**Comment by dongahn** [comment]
On TOSS3, LaunchMON's backend API is stuck in its target process control logic in [here]( https://github.com/LLNL/LaunchMON/blob/master/launchmon/src/linux/lmon_api/lmon_be_sync_mpi_generic.cxx#L251).

It is been a while, but I recall this additional `waitpid ()` was needed because `slurmsteps` sends an additional `SIGCONT` to each MPI process to support `MPIR_partial_attach_ok`: the spec is [here](https://www.mpi-forum.org/docs/mpir-specification-10-11-2010.pdf)

SLURM's MPI job-debugger synchronization sequence is implemented in https://github.com/chaos/slurm/blob/master/src/slurmd/slurmstepd/pdebug.c. I have a note from a developer explaining this:

>pdebug_stop_current() calls ptrace(PTRACE_TRACEME) to get the
child process to stop at exec(2).

> During a request for parallel debug, slurmd will then wait for the
> process to stop with waitpid(2), (See pdebug_trace_process()) send
> SIGSTOP to the task, then call ptrace(PTRACE_DETACH). The child will
> wake up, but immediately stop again because of the pending SIGSTOP, and
> the parallel app will be ready for an attach from another debugger.

Then, as part of MPIR_partial_attach_ok support, the additional SIGCONT is sent to each MPI process so that SLURM can continue those processes that are not attached by the debugger.

If this is a slurm issue on TOSS3 environment, TotalView's subset debugging should fail as well. In fact, my brief testing shows it fails on `opal`

I need to look into what's happening with SLURM's `MPIR_partial_attach_ok` support/

**Comment by dongahn** [comment]
It seems the SLURM code responsible of this https://github.com/chaos/slurm/blob/master/src/slurmd/slurmstepd/pdebug.c#L161

If I read this code right and now that I think about this some more, I am not sure why LaunchMON backend is getting `SIGCONT` on TOSS2 system either. Slurmstepd should only send this signal to the process that are **not** traced by the debugger because of the following  `if ((flags & CLONE_PTRACE) == 0)` statement. 

In any case, according to the man page for proc (5) of both TOSS 2 (2.6.32) and TOSS 3 (3.10.0):

```
       /proc/[pid]/stat
              Status information about the process.  This is used by ps(1).  It is defined in /usr/src/linux/fs/proc/array.c.

              The fields, in order, with their proper scanf(3) format specifiers, are:

              pid %d      The process ID.

              comm %s     The filename of the executable, in parentheses.  This is visible whether or not the executable is swapped out.

              state %c    One character from the string "RSDZTW" where R is running, S is sleeping in an interruptible wait,  D  is  waiting  in
                          uninterruptible disk sleep, Z is zombie, T is traced or stopped (on a signal), and W is paging.

              ppid %d     The PID of the parent.

              pgrp %d     The process group ID of the process.

              session %d  The session ID of the process.

              tty_nr %d   The  controlling  terminal  of the process.  (The minor device number is contained in the combination of bits 31 to 20
                          and 7 to 0; the major device number is in bits 15 t0 8.)

              tpgid %d    The ID of the foreground process group of the controlling terminal of the process.

              flags %u (%lu before Linux 2.6.22)
                          The kernel flags word of the process.  For bit meanings, see the PF_* defines in <linux/sched.h>.  Details  depend  on
                          the kernel version.
```

So the `flags` field is now unsigned integer instead of long unsigned integer. So, this can be harmful and could lead to undefined behavior...?

On TOSS2, the following `if ((flags & CLONE_PTRACE) == 0)` statement could be evaluated to be true even if the target process is being traced, causing slurm to always send `SIGCONT`. (Perhaps LaunchMON's additional `waitpid()` was added to work around this condition.)

On TOSS3, the same statement could somehow be evaluated to be false even thought the target process is not being traced, causing slurm not to send `SIGCONT` at all. This then would fail TotalView's subset debugging. 

I need to bounce this to @lipari and @grondo.

**Comment by grondo** [comment]
Actual code we're running on TOSS systems should be from this branch:
 https://github.com/chaos/slurm/blob/slurm-2.3.2.chaos/src/slurmd/slurmstepd/pdebug.c

However, I'm not sure there is much difference in ours vs chaos/slurm master branch.

That code you reference seems like it would be very brittle, and I'm not sure why it is needed over the `waitpid(2) WIFSTOPPED` check that is done when `CLONE_PTRACE` is not defined. Of course, there is no hint in the commit that added the code:
 
https://github.com/chaos/slurm/commit/8985821c4d3b894bf9d794ca2527341bd17bcba9

We could check upstream code for any differences, becuase I would assume upstream slurm has been tested on newer kernels (but you never know!)

 https://github.com/SchedMD/slurm/blob/master/src/slurmd/slurmstepd/pdebug.c

Another ideas is to try an experiment and disable the code under `#ifdef CLONE_PTRACE` on TOSS3. 

Do you have a standalone test for the failing case?

**Comment by dongahn** [comment]
I think the best test case is TotalView's subset debugging, but that's a GUI testing. So I'm not sure how good this is for you. BTW, is this something that you will want to look into or delegate to someone else? I know you are -- and we are :-) busy with flux. 

I can create a standalone based on LauchMON code but this will take some time. If GUI testing doesn't work for you, let me know.

FWIW, I found MPIR_partitial_attach_ok support was introduced here: https://github.com/chaos/slurm/blob/slurm-2.3.2.chaos/NEWS#L1507

**Comment by dongahn** [comment]
> That code you reference seems like it would be very brittle, and I'm not sure why it is needed over the waitpid(2) WIFSTOPPED check that is done when CLONE_PTRACE is not defined. Of course, there is no hint in the commit that added the code:

I think the idea is not to send `SIGCONT` to those processes that have been attached by the debugger, fearing a side effect. Note that this is for MPIR_partitial_attach_ok support.

**Comment by grondo** [comment]
>  I think the idea is not to send SIGCONT to those processes that have been attached by the debugger, fearing a side effect. Note that this is for MPIR_partitial_attach_ok support.

But I'm not sure it does event that (does `CLONE_PTRACE` indicate the debugger has been attached? I don't think so, and there is no documentation that says so). Also, I'm concerned that the code is matching  `clone(2)` flags to `proc(5)` process flags, which are not the same as `task->flags` defined as `PF_*` flags from kernel *source* `include/linux/sched.h`. These flags are not guaranteed to match are they?

I'm probably missing something completely, but my feeling is that the code under `#ifdef CLONE_PTRACE` doesn't work at all as designed... I assume it was tested but perhaps only accidentally works?

**Comment by dongahn** [comment]
It does sound like a brittle code and may explain why we see different behavior on toss3.

We either need to find a more reliable way to test if a target process is traced by a debugger or disable this code within slurm and work around the additional SIGCONT at the tool level.

Launchmon can deal with it and TotalView seems ok with the additional signal. Don't know about ddt...


________________________________

**Comment by grondo** [comment]
There is `TracerPid` from `/proc/PID/status` -- from `proc(5)`:
```
* TracerPid: PID of process tracing this process (0 if not
                being traced).
```

Just need to verify if by "tracing this process" they specifically mean `ptrace(2)`

**Comment by grondo** [comment]
Yeah, it does look like `TracerPid` will report the PID of the ptrace parent if the task is being traced, otherwise `0`

**Comment by dongahn** [comment]
Yes, it does look like `TracerPid` based checking should be much more reliable.

**Comment by dongahn** [comment]
@grondo or @lipari: what is the logistics of applying a patch to slurm and testing/deploying it on LC systems one of these days?

**Comment by dongahn** [comment]
@lee218llnl: as we discussed, while a slurm patch is worked on, I will make a configure time option to LaunchMON so that it can work in either case. This way, we can keep packaging and testing STAT/Spindle on TOSS3 without being blocked by this.

**Comment by grondo** [comment]
> @grondo or @lipari: what is the logistics of applying a patch to slurm and testing/deploying it on LC systems one of these days?

I would have to defer to @lipari on that one. If you create a fork of chaos/slurm branch mentioned above and work up the patch I'm sure @lipari would merge it. It is easy to test just a new slurmd by changing slurm.conf on a subset of nodes temporarily, and I could help with that.

**Comment by dongahn** [comment]
@grondo: Thanks. I think this should be an easy enough fix. I thought testing could be more difficult but with your help, that should be easy as well. I will see what I can.

**Comment by dongahn** [comment]
OK. I talked @lipari. I will create and test a patch for SLURM. 

BTW, the following SLURM dev/test method is from @lipari. I am leaving his note here since this seems useful for triaging other SLURM related issues for our tools. I tested this under my environment:

> Here are the rough steps to test slurm on a local cluster.  It is cobbled together, so let me know if I missed something.

> 1.  From your home directory, run:  git clone --branch= slurm-2.3.3.chaos git@github.com:chaos/slurm.git
2.  mkdir ~/log ~/spool ~/slurm_state
3.  mkdir a ~/slurminst directory can step into it
4.  run ~/slurm/configure --enable-debug --prefix=/g/g0/dahn/slurminst
5.  make, make install

> Now you're going to have to create a /g/g0/dahn/slurminst/etc/slurm.conf file.  It should look like this:

> ClusterName=mycluster
ControlMachine=localhost
ControlAddr=localhost

> AuthType=auth/munge
CryptoType=crypto/munge
ProctrackType=proctrack/linuxproc
SlurmUser=dahn
SlurmctldPidFile=/g/g0/dahn/slurm_state/slurmctld.pid
SlurmctldPort=21016
SlurmdPidFile=/g/g0/dahn/slurm_state/slurmd-%n.pid
SlurmdPort=21017
SlurmdSpoolDir=/g/g0/dahn/spool
SlurmdUser=dahn
StateSaveLocation=/g/g0/dahn/slurm_state
SwitchType=switch/none


> \# SCHEDULING
FastSchedule=1
SelectType=select/linear

> \# LOGGING
DebugFlags=SelectType,Backfill
SlurmSchedLogFile=/g/g0/dahn/log/slurmsched.log
SlurmSchedLogLevel=3
SlurmctldDebug=5
SlurmctldLogFile=/g/g0/dahn/log/slurmctld.log
SlurmdDebug=9
SlurmdLogFile=/g/g0/dahn/log/slurmd-%n.log

> \# COMPUTE NODES
NodeName=DEFAULT Sockets=2 CoresPerSocket=2 ThreadsPerCore=1 RealMemory=15701 State=UNKNOWN

> NodeName=mycluster1 NodeAddr=localhost Port=21019
NodeName=mycluster2 NodeAddr=localhost Port=21020
NodeName=mycluster3 NodeAddr=localhost Port=21021
NodeName=mycluster4 NodeAddr=localhost Port=21022

> PartitionName=DEFAULT Shared=NO
PartitionName=pbatch Nodes=mycluster[1-4] Default=YES MaxTime=12:00:00 State=UP


> At this point, you need to start up the slurmctd and 4 slurmd's:

> I do these in separate windows:

> /g/g0/dahn/slurminst/sbin/slurmctld -Dvv
/g/g0/dahn/slurminst/sbin/slurmd -N mycluster1 -Dvv
/g/g0/dahn/slurminst/sbin/slurmd -N mycluster2 -Dvv
/g/g0/dahn/slurminst/sbin/slurmd -N mycluster3 -Dvv
/g/g0/dahn/slurminst/sbin/slurmd -N mycluster4 -Dvv

> Now, you can cd to /g/g0/dahn/slurminst/bin and run your commands:

> ./sinfo
./squeue
./srun ...


> When you're done, invoke:
./scontrol shutdown
And everything dies.

**Comment by dongahn** [comment]
For tool testing, I needed to use real hostname. E.g., my final `slurm.conf` on opal was:

> ClusterName=opal
ControlMachine=opal19
ControlAddr=opal19

> AuthType=auth/munge
CryptoType=crypto/munge
ProctrackType=proctrack/linuxproc
SlurmUser=dahn
SlurmctldPidFile=/g/g0/dahn/slurm_state/slurmctld.pid
SlurmctldPort=21016
SlurmdPidFile=/g/g0/dahn/slurm_state/slurmd-%n.pid
SlurmdPort=21017
SlurmdSpoolDir=/g/g0/dahn/spool
SlurmdUser=dahn
StateSaveLocation=/g/g0/dahn/slurm_state
SwitchType=switch/none


> \# SCHEDULING
FastSchedule=1
SelectType=select/linear

> \# LOGGING
DebugFlags=SelectType,Backfill
SlurmSchedLogFile=/g/g0/dahn/log/slurmsched.log
SlurmSchedLogLevel=3
SlurmctldDebug=5
SlurmctldLogFile=/g/g0/dahn/log/slurmctld.log
SlurmdDebug=9
SlurmdLogFile=/g/g0/dahn/log/slurmd-%n.log

> \# COMPUTE NODES
NodeName=DEFAULT Sockets=2 CoresPerSocket=2 ThreadsPerCore=1 RealMemory=15701 State=UNKNOWN

> NodeName=opal19 NodeAddr=opal19 Port=21019
NodeName=opal20 NodeAddr=opal20 Port=21021
#NodeName=mycluster3 NodeAddr=localhost Port=21021
#NodeName=mycluster4 NodeAddr=localhost Port=21022

> PartitionName=DEFAULT Shared=NO

I also needed to specify `--mpi=mvapich` to the side-installed srun for a MPI job compiled with mvapich.

**Comment by dongahn** [comment]
A patch has been submitted to SLURM: [here](https://github.com/chaos/slurm/pull/59)
