### ISSUE TITLE
Boostrap Failure on trinitite

### ISSUE THREAD

**Issue by lee218llnl** [LLNL/LaunchMON#28]
@dongahn I ran into issues trying to boostrap on the LANL/Sandia trinitite system. I haven't tried to debug this yet. Let me know if there's any diagnostic information I should try to gather to help narrow this down.

./bootstrap 
Running aclocal ...  
configure.ac:140: warning: macro 'AM_PATH_LIBGCRYPT' not found in library
fatal: Not a git repository (or any parent up to mount point /users/gregoryl)  
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set). 
configure.ac:92: error: AC_INIT should be called with package and version arguments  
/usr/share/aclocal-1.13/init.m4:23: AM_INIT_AUTOMAKE is expanded from...  
configure.ac:92: the top level  
autom4te: /usr/bin/m4 failed with exit status: 1  
aclocal: error: echo failed with exit status: 1  
Running libtoolize ...  
Running autoheader ...  
fatal: Not a git repository (or any parent up to mount point /users/gregoryl)  
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set). 
Running automake ...  
fatal: Not a git repository (or any parent up to mount point /users/gregoryl)  
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set). 
configure.ac: error: no proper invocation of AM_INIT_AUTOMAKE was found.  
configure.ac: You should verify that configure.ac invokes AM_INIT_AUTOMAKE,
configure.ac: that aclocal.m4 is present in the top-level directory,  
configure.ac: and that aclocal.m4 was recently regenerated (using aclocal) 
/usr/share/automake-1.13/am/depend2.am: error: am__fastdepCXX does not appear in AM_CONDITIONAL  
/usr/share/automake-1.13/am/depend2.am:   The usual way to define 'am__fastdepCXX' is to add 'AC_PROG_CXX'  
/usr/share/automake-1.13/am/depend2.am:   to 'configure.ac' and run 'aclocal' and 'autoconf' again  
/usr/share/automake-1.13/am/depend2.am: error: AMDEP does not appear in AM_CONDITIONAL  
/usr/share/automake-1.13/am/depend2.am:   The usual way to define 'AMDEP' is to add one of the compiler tests  
/usr/share/automake-1.13/am/depend2.am:     AC_PROG_CC, AC_PROG_CXX, AC_PROG_OBJC, AC_PROG_OBJCXX,  
/usr/share/automake-1.13/am/depend2.am:     AM_PROG_AS, AM_PROG_GCJ, AM_PROG_UPC  
/usr/share/automake-1.13/am/depend2.am:   to 'configure.ac' and run 'aclocal' and 'autoconf' again  
launchmon/src/linux/lmon_api/Makefile.am:47: error: WITH_CIOD does not appear in AM_CONDITIONAL  
launchmon/src/linux/lmon_api/Makefile.am:58: error: Libtool library used but 'LIBTOOL' is undefined  
launchmon/src/linux/lmon_api/Makefile.am:58:   The usual way to define 'LIBTOOL' is to add 'LT_INIT'
launchmon/src/linux/lmon_api/Makefile.am:58:   to 'configure.ac' and run 'aclocal' and 'autoconf' again.
launchmon/src/linux/lmon_api/Makefile.am:58:   If 'LT_INIT' is in 'configure.ac', make sure
launchmon/src/linux/lmon_api/Makefile.am:58:   its definition is in aclocal's search path.
test/src/Makefile.am:48: error: WITH_CIOD does not appear in AM_CONDITIONAL
test/src/Makefile.am:53: error: WITH_TEST_INSTALLED does not appear in AM_CONDITIONAL
test/src/Makefile.am:94: warning: compiling 'LE_model_checker.c' with per-target flags requires 'AM_PROG_CC_C_O' in 'configure.ac'
/usr/share/automake-1.13/am/depend2.am: error: am__fastdepCC does not appear in AM_CONDITIONAL
/usr/share/automake-1.13/am/depend2.am:   The usual way to define 'am__fastdepCC' is to add 'AC_PROG_CC'
/usr/share/automake-1.13/am/depend2.am:   to 'configure.ac' and run 'aclocal' and 'autoconf' again
tools/Makefile.am:39: error: WITH_CIOD does not appear in AM_CONDITIONAL
tools/Makefile.am:42: error: WITH_ALPS does not appear in AM_CONDITIONAL
tools/cobo/src/Makefile.am:36: error: Libtool library used but 'LIBTOOL' is undefined
tools/cobo/src/Makefile.am:36:   The usual way to define 'LIBTOOL' is to add 'LT_INIT'
tools/cobo/src/Makefile.am:36:   to 'configure.ac' and run 'aclocal' and 'autoconf' again.
tools/cobo/src/Makefile.am:36:   If 'LT_INIT' is in 'configure.ac', make sure
tools/cobo/src/Makefile.am:36:   its definition is in aclocal's search path.
tools/handshake/Makefile.am:41: error: Libtool library used but 'LIBTOOL' is undefined
tools/handshake/Makefile.am:41:   The usual way to define 'LIBTOOL' is to add 'LT_INIT'
tools/handshake/Makefile.am:41:   to 'configure.ac' and run 'aclocal' and 'autoconf' again.
tools/handshake/Makefile.am:41:   If 'LT_INIT' is in 'configure.ac', make sure
tools/handshake/Makefile.am:41:   its definition is in aclocal's search path.
Running autoconf ...
configure.ac:36: error: possibly undefined macro: X_AC_MW_HOSTLIST
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:59: error: possibly undefined macro: AC_SUBST
configure.ac:91: error: possibly undefined macro: AM_INIT_AUTOMAKE
configure.ac:94: error: possibly undefined macro: AM_SILENT_RULES
configure.ac:96: error: possibly undefined macro: AM_MAINTAINER_MODE
configure.ac:101: error: possibly undefined macro: X_AC_PLATFORM
configure.ac:102: error: possibly undefined macro: X_AC_SLURM_MPAO_WR
configure.ac:107: error: possibly undefined macro: X_AC_ENABLE_DEBUG
configure.ac:112: error: possibly undefined macro: X_AC_ENABLE_VERBOSE
configure.ac:119: error: possibly undefined macro: AC_DEFINE
configure.ac:140: error: possibly undefined macro: AM_PATH_LIBGCRYPT
configure.ac:150: error: possibly undefined macro: AC_MSG_ERROR
configure.ac:157: error: possibly undefined macro: X_AC_HANDSHAKE
configure.ac:162: error: possibly undefined macro: X_AC_TRACING_COST
configure.ac:168: error: possibly undefined macro: X_AC_TESTNNODES
configure.ac:169: error: possibly undefined macro: X_AC_NCORE_SMP
configure.ac:170: error: possibly undefined macro: X_AC_TEST_RM
configure.ac:172: error: possibly undefined macro: X_AC_TEST_INSTALLED
configure.ac:179: error: possibly undefined macro: AC_PROG_LIBTOOL
configure.ac:181: error: possibly undefined macro: AM_PROG_CC_C_O
mv: cannot stat ‘aclocal.m4’: No such file or directory
Now run ./configure.

**Comment by dongahn** [comment]
@lee218llnl: Here is my first guess. With respect to 

```
configure.ac:140: warning: macro 'AM_PATH_LIBGCRYPT' not found in library
```

`AM_PATH_LIBGCRYPT` m4 macro should be provided by `libgcrypt-devel`. For example, on our cab system, 

```
rpm -ql libgcrypt-devel-1.4.5-11.el6_4.x86_64

/usr/bin/dumpsexp
/usr/bin/hmac256
/usr/bin/libgcrypt-config
/usr/include/gcrypt-module.h
/usr/include/gcrypt.h
/usr/lib64/libgcrypt.so
/usr/share/aclocal/libgcrypt.m4
/usr/share/doc/libgcrypt-devel-1.4.5
/usr/share/doc/libgcrypt-devel-1.4.5/COPYING
/usr/share/info/gcrypt.info.gz
```

This rpm installs `libgcrypt.m4` into /usr/share/aclocal and

```
cab690{dahn}25: cat /usr/share/aclocal/libgcrypt.m4 
<CUT>
dnl AM_PATH_LIBGCRYPT([MINIMUM-VERSION,
dnl                   [ACTION-IF-FOUND [, ACTION-IF-NOT-FOUND ]]])
dnl Test for libgcrypt and define LIBGCRYPT_CFLAGS and LIBGCRYPT_LIBS.
dnl MINIMUN-VERSION is a string with the version number optionalliy prefixed
dnl with the API version to also check the API compatibility. Example:
dnl a MINIMUN-VERSION of 1:1.2.5 won't pass the test unless the installed 
dnl version of libgcrypt is at least 1.2.5 *and* the API number is 1.  Using
dnl this features allows to prevent build against newer versions of libgcrypt
dnl with a changed API.
dnl
```

Could you type in `rpm -qa | grep libgcrypt` in Trinitite to see if they have a `libgcrypt-devel` rpm package installed first? If not, (or the version is too old), perhaps you should put in a request to install or update it... 

W/ respect to 

```
fatal: Not a git repository (or any parent up to mount point /users/gregoryl)
```

I have no idea why this msg is printed. Googling suggests that this msg is hit when you  perform a git command which then fails when it cannot find a git repo. `bootstrap` uses no git command at least directly... 

In any case, as the first step, I would check that `libgcrypt-devel` rpm presence/version.

I also noticed that `README.md` says LaunchMON's dependency is`libgcrypt` not `libgcrypt-devel`. So if this is indeed the root cause, I will update the README as well.

**Comment by dongahn** [comment]
Seems this was a system issue.
