### ISSUE TITLE
errors occured when i ran ./bootstrap on my ubuntu-i386

### ISSUE THREAD

**Issue by buaaluwentao** [LLNL/LaunchMON#31]
I ran ./bootstrap after I extract the Launchmon.zip, but unluckily,I got this error list:

fatal: Not a git repository (or any parent up to mount point /mount)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
configure.ac:92: error: AC_INIT should be called with package and version arguments
/usr/share/aclocal-1.14/init.m4:29: AM_INIT_AUTOMAKE is expanded from...
configure.ac:92: the top level
autom4te: /usr/bin/m4 failed with exit status: 1
aclocal: error: echo failed with exit status: 1
fatal: Not a git repository (or any parent up to mount point /mount)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: Not a git repository (or any parent up to mount point /mount)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
configure.ac: error: no proper invocation of AM_INIT_AUTOMAKE was found.
configure.ac: You should verify that configure.ac invokes AM_INIT_AUTOMAKE,
configure.ac: that aclocal.m4 is present in the top-level directory,
configure.ac: and that aclocal.m4 was recently regenerated (using aclocal)
configure.ac:80: installing 'config/config.guess'
configure.ac:80: installing 'config/config.sub'
configure.ac:183: installing 'config/install-sh'
launchmon/src/linux/Makefile.am:56: warning: source file '$(API_SRC_DIR)/lmon_lmonp_msg.cxx' is in a subdirectory,
launchmon/src/linux/Makefile.am:56: but option 'subdir-objects' is disabled
automake: warning: possible forward-incompatibility.
automake: At least a source file is in a subdirectory, but the 'subdir-objects'
automake: automake option hasn't been enabled.  For now, the corresponding output
automake: object file(s) will be placed in the top-level directory.  However,
automake: this behaviour will change in future Automake versions: they will
automake: unconditionally cause object files to be placed in the same subdirectory
automake: of the corresponding sources.
automake: You are advised to start using 'subdir-objects' option throughout your
automake: project, to avoid future incompatibilities.
launchmon/src/linux/Makefile.am:56: warning: source file '$(API_SRC_DIR)/lmon_say_msg.cxx' is in a subdirectory,
launchmon/src/linux/Makefile.am:56: but option 'subdir-objects' is disabled
launchmon/src/linux/Makefile.am:56: warning: source file '$(BASE_SRC_DIR)/sdbg_self_trace.cxx' is in a subdirectory,
launchmon/src/linux/Makefile.am:56: but option 'subdir-objects' is disabled
launchmon/src/linux/Makefile.am:56: warning: source file '$(BASE_SRC_DIR)/sdbg_opt.cxx' is in a subdirectory,
launchmon/src/linux/Makefile.am:56: but option 'subdir-objects' is disabled
launchmon/src/linux/Makefile.am:56: warning: source file '$(BASE_SRC_DIR)/sdbg_rm_map.cxx' is in a subdirectory,
launchmon/src/linux/Makefile.am:56: but option 'subdir-objects' is disabled
launchmon/src/linux/Makefile.am: installing 'config/depcomp'
/usr/share/automake-1.14/am/depend2.am: error: am__fastdepCXX does not appear in AM_CONDITIONAL
/usr/share/automake-1.14/am/depend2.am:   The usual way to define 'am__fastdepCXX' is to add 'AC_PROG_CXX'
I did nothing to the source code ,version of the dependencies and tools as follows:
automake (GNU automake) 1.14.1
autoconf (GNU Autoconf) 2.69
libtoolize (GNU libtool) 2.4.2
boost 1.63
ii  libelf1:i386    0.158-0ubuntu5
ii  libmunge2       0.5.11-1ubuntu1 
ii  libgcrypt11:i386     1.5.3-2ubuntu4
ii  libgpg-error0:i386    1.12-0.2ubuntu1
ii   munge     0.5.11-1ubuntu1
ii  libgcrypt11-dev    1.5.3-2ubuntu4.4
git version 1.9.1 (git was installed ,but I did not use it.) 
I do all that on my ubuntu14.04 -i386,appreciate any help,very thank you.

very thank you, dongahn
Yes ， I tried the laterest version，but I still got：
libtool: install: warning: relinking `libmonbeapi.la'
libtool: install: warning: relinking `libmonfeapi.la'
libtool: install: warning: relinking `libmonmwapi.la'
but I can almost confirm the software was installed rightly，thank you very much.

**Comment by dongahn** [comment]
Could you try rhis with the latest release tarball? https://github.com/LLNL/LaunchMON/releases
